# Generated by Django 4.2.20 on 2025-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cates", "0002_yolotask"),
    ]

    operations = [
        migrations.AddField(
            model_name="yolotask",
            name="epochs",
            field=models.IntegerField(default=10, verbose_name="迭代轮次"),
        ),
        migrations.AlterField(
            model_name="yolotask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="yolotask",
            name="status",
            field=models.IntegerField(
                choices=[(1, "等待"), (2, "训练"), (3, "完成"), (4, "取消")],
                default=1,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="yolotask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
