# Generated by Django 4.2.20 on 2025-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cates", "0003_yolotask_epochs_alter_yolotask_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="extra",
            field=models.TextField(blank=True, null=True, verbose_name="扩展"),
        ),
        migrations.AlterField(
            model_name="yolotask",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Training"),
                    (3, "Completed"),
                    (4, "Canceled"),
                ],
                default=1,
                verbose_name="状态",
            ),
        ),
    ]
