# Generated by Django 4.2.20 on 2025-04-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cates", "0004_category_extra_alter_yolotask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="en_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="英文"
            ),
        ),
    ]
