"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#!@f04+*5ct8^nm+$xpm8o=zs-g7=cswtcyt^)-(-d@=e8d3c-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# API Auth
VERIFY_FLAG = 100

EMBEDDING_MODEL = 'torch_mnv3'
MILVUS_DATA = '960_collection'

# 图片向量处理模型
# EMBEDDING_MODEL = '1'
# 图片向量存储结合
# MILVUS_DATA = '1'

# 缓存链接配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

CELERY_BROKER_URL = 'redis://localhost:6379/2'  # Redis 作为消息代理

CELERY_RESULT_BACKEND = 'redis://localhost:6379/2'  # Redis 作为结果存储

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account.apps.AccountConfig',
    'goods.apps.GoodsConfig',
    'cates.apps.CatesConfig',
    'home.apps.HomeConfig',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'goods_vectros',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',  # 确保客户端使用 UTF-8
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True
SIMPLEUI_HOME_INFO = False
SIMPLEUI_LOGO = "/assets/images/logo.png"
SIMPLEUI_FAVICON = '/assets/images/logo.png'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/assets/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# 确保你的静态文件存放在这里
STATICFILES_DIRS = [BASE_DIR / "assets"]

AUTH_USER_MODEL = 'account.Consumer'
SIMPLEUI_STATIC_OFFLINE = True

MEDIA_URL = '/media/'  # 用于访问上传文件的 URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 上传文件的存储路径

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['品类管理', '模型微调', '商品管理', '任务管理', '管理权限', '下载训练文件'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'name': '下载训练文件',
        'icon': 'fa fa-solid fa-download',
        'url': '/cates/yolo_task/down_datasets',
        'target': '_blank',
    }, {
        'name': '品类管理',
        'icon': 'fa fa-solid fa-bandage',
        'url': 'cates/category',
    }, {
        'name': '模型微调',
        'icon': 'fa-solid fa-train',
        'url': 'cates/yolotask',
    }, {
        'app': 'auth',
        'name': '管理权限',
        'icon': 'fa-solid fa-user-shield',
        'models': [{
            'name': '用户列表',
            'icon': 'fa fa-vcard',
            'url': 'account/consumer/'
        },{
            'name': '管理权限',
            'icon': 'fa-solid fa-building-shield',
            'url': 'auth/group/'
        }]
    },  {
            'name': '商品管理',
            'url': 'goods/goods/',
            'icon': 'fa fa-solid fa-swatchbook'
    },  {
            'name': '任务管理',
            'icon': 'fas fa-tasks',
            'models': [
                {
                    'name': '周期性任务',
                    'icon': 'fas fa-clock',
                    'url': 'django_celery_beat/periodictask/',
                },
                {
                    'name': '间隔任务',
                    'icon': 'fas fa-hourglass',
                    'url': 'django_celery_beat/intervalschedule/',
                },
                {
                    'name': 'Crontab 任务',
                    'icon': 'fas fa-calendar-alt',
                    'url': 'django_celery_beat/crontabschedule/',
                },
            ]
        },]
}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'  # 设置时区
# django-celery-beat 配置
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
