# Generated by Django 4.2.20 on 2025-03-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image_url',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/%Y%m%d/', verbose_name='图片文件'),
        ),
    ]
