# Generated by Django 4.2.20 on 2025-03-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_is_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_vector',
            field=models.BooleanField(default=False, verbose_name='图片向量'),
        ),
    ]
