# Generated by Django 4.2.20 on 2025-03-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_image_url_alter_goods_is_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['id', 'name'], name='goods_id_bd961a_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
